services:
  - type: web
    name: taiz-lost-and-found
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Taiz Lost and Found"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://taiz-lost-and-found.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
    disk:
      name: sqlite-data
      mountPath: /var/www/database
      sizeGB: 1
